x = str("Hello World")
print(x)
x = int(5)
print(x)
x = float(5)
print(x)
# x = complex(1j)
# print(x)
x = list(("apple", "banana", "cherry"))
print(x)
x = tuple(("cherry", "banana", "apple"))
print(x)
x = range(6)
print(x)
x = dict(name="John", age=36)
print(x)
# x = set(("apple", "banana", "cherry"))
# print(x)
x = frozenset(("apple", "banana", "cherry"))
print(x)
x = bool("true")
print(x)
x = bytes(5)
print(x)
x = bytearray(5)
print(x)
x = memoryview(bytes(5))
print(x)
